name: Deploy dev server

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_SSH_ID }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_SSH_PORT }}
          script: |
            cd server.career.belivvr.com
            git pull
            yarn
            yarn build
            pm2 restart server
